### ISSUE TITLE
Foreign Key Error by when deactivating information security risks

### ISSUE THREAD

**Issue by KonzeptAcht** [monarc-project/MonarcAppFO#358]
**Describe the bug**
Deactivating entries in the knowledge base under the Information Security tab leads to an error message. The error can be reset in the my.monarc instance.

**To Reproduce**
1. Go to knowledge base
2. Click on Information Security Tab
3. click on the hook to deactivate the entry

**Expected behavior**
Deactivating the information security risk

**Screenshots**
<img width="1734" alt="image" src="https://user-images.githubusercontent.com/47662401/122941601-d306ba80-d375-11eb-8227-6a1b9e554eb6.png">

**Desktop (please complete the following information):**

| Questions                                | Answers
|-----------------------------------------|--------------------
| Type of issue                           | Bug
| OS version (server)                 | Ubuntu 18.04/Ubuntu 20.04
| OS version (client)                   | MacOS, Win10, Debian
| PHP version                             | 7.3
| MONARC version / git hash     | 2.10.2
| Browser                                    | Firefox, Chrome, Safari

**Additional context**
`Possibly unhandled rejection: {"data":{"errors":[{"message":"An exception occurred while executing 'UPDATE amvs SET status = ?, updater = ?, threat_id = ?, anr_id = ?, vulnerability_id = ?, updated_at = ? WHERE uuid = ? AND anr_id = ?' with params [false, \"Admin Admin\", null, null, null, \"2021-06-22 16:22:31\", \"a8bc5530-97b1-4214-a8cf-c5b1d0680f7b\", \"2\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`monarc_cli`.`instances_risks`, CONSTRAINT `instances_risks_ibfk_5` FOREIGN KEY (`amv_id`, `anr_id`) REFERENCES `amvs` (`uuid`, `anr_id`) ON DELETE CASCADE)","error":"error-exception","exception":{"class":"Doctrine\\DBAL\\Exception\\ForeignKeyConstraintViolationException","file":"/var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","line":53,"message":"An exception occurred while executing 'UPDATE amvs SET status = ?, updater = ?, threat_id = ?, anr_id = ?, vulnerability_id = ?, updated_at = ? WHERE uuid = ? AND anr_id = ?' with params [false, \"Admin Admin\", null, null, null, \"2021-06-22 16:22:31\", \"a8bc5530-97b1-4214-a8cf-c5b1d0680f7b\", \"2\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`monarc_cli`.`instances_risks`, CONSTRAINT `instances_risks_ibfk_5` FOREIGN KEY (`amv_id`, `anr_id`) REFERENCES `amvs` (`uuid`, `anr_id`) ON DELETE CASCADE)","stacktrace":"#0 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(172): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException('An exception oc...', Object(Doctrine\\DBAL\\Driver\\PDOException))\n#1 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(151): Doctrine\\DBAL\\DBALException::wrapException(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'An exception oc...')\n#2 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1087): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery(Object(Doctrine\\DBAL\\Driver\\PDOMySql\\Driver), Object(Doctrine\\DBAL\\Driver\\PDOException), 'UPDATE amvs SET...', Array)\n#3 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(505): Doctrine\\DBAL\\Connection->executeUpdate('UPDATE amvs SET...', Array, Array)\n#4 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(394): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->updateTable(Object(Monarc\\FrontOffice\\Model\\Entity\\Amv), 'amvs', Array, NULL)\n#5 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1172): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->update(Object(Monarc\\FrontOffice\\Model\\Entity\\Amv))\n#6 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(407): Doctrine\\ORM\\UnitOfWork->executeUpdates(Object(Doctrine\\ORM\\Mapping\\ClassMetadata))\n#7 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(371): Doctrine\\ORM\\UnitOfWork->commit(NULL)\n#8 /var/lib/monarc/fo/vendor/monarc/core/src/Model/Db.php(345): Doctrine\\ORM\\EntityManager->flush()\n#9 /var/lib/monarc/fo/vendor/monarc/core/src/Model/Db.php(325): Monarc\\Core\\Model\\Db->flush()\n#10 /var/lib/monarc/fo/vendor/monarc/core/src/Model/Table/AbstractEntityTable.php(311): Monarc\\Core\\Model\\Db->save(Object(Monarc\\FrontOffice\\Model\\Entity\\Amv), true)\n#11 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrAmvService.php(201): Monarc\\Core\\Model\\Table\\AbstractEntityTable->save(Object(Monarc\\FrontOffice\\Model\\Entity\\Amv))\n#12 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Controller/ApiAnrAbstractController.php(169): Monarc\\FrontOffice\\Service\\AnrAmvService->patch(Array, Array)\n#13 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(409): Monarc\\FrontOffice\\Controller\\ApiAnrAbstractController->patch(Array, Array)\n#14 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\\Mvc\\Controller\\AbstractRestfulController->onDispatch(Object(Laminas\\Mvc\\MvcEvent))\n#15 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\\EventManager\\EventManager->triggerListeners(Object(Laminas\\Mvc\\MvcEvent), Object(Closure))\n#16 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\\Mvc\\MvcEvent))\n#17 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(312): Laminas\\Mvc\\Controller\\AbstractController->dispatch(Object(Laminas\\Http\\PhpEnvironment\\Request), Object(Laminas\\Http\\PhpEnvironment\\Response))\n#18 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/DispatchListener.php(139): Laminas\\Mvc\\Controller\\AbstractRestfulController->dispatch(Object(Laminas\\Http\\PhpEnvironment\\Request), Object(Laminas\\Http\\PhpEnvironment\\Response))\n#19 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(321): Laminas\\Mvc\\DispatchListener->onDispatch(Object(Laminas\\Mvc\\MvcEvent))\n#20 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(178): Laminas\\EventManager\\EventManager->triggerListeners(Object(Laminas\\Mvc\\MvcEvent), Object(Closure))\n#21 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\\EventManager\\EventManager->triggerEventUntil(Object(Closure), Object(Laminas\\Mvc\\MvcEvent))\n#22 /var/lib/monarc/fo/public/index.php(34): Laminas\\Mvc\\Application->run()\n#23 {main}"}}]},"status":500,"config":{"method":"PATCH","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"status":false},"url":"api/client-anr/2/amvs/a8bc5530-97b1-4214-a8cf-c5b1d0680f7b","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","token":"76fb2e416a34c51e6d6bb88c56b98ed40e4436c69db83dd8203160d1efd7c80999.21480463"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete","resource":{"status":false}}`

**Comment by ruslanbaidan** [comment]
Fixed and will be delivered within the current release.
PR: https://github.com/monarc-project/zm-client/pull/54/files

**Comment by KonzeptAcht** [comment]
@ruslanbaidan 

i just checked again to make sure everything is working properly. Unfortunately we still have an error even in the 2.10.4. Now it's about an integrity violation because 'threat_id' cannot be null. Could you take another look here? Or should I open a new issue?

Thanks Marc

`[Error] Failed to load resource: the server responded with a status of 500 (Internal Server Error) (1744ac79-a84e-4f7d-bf30-34b9d90b9144, line 0)
[Error] Possibly unhandled rejection: {"data":{"errors":[{"message":"An exception occurred while executing 'UPDATE amvs SET status = ?, updater = ?, threat_id = ?, anr_id = ?, vulnerability_id = ?, updated_at = ? WHERE uuid = ? AND anr_id = ?' with params [false, \"Admin Admin\", null, null, null, \"2021-07-07 11:27:24\", \"1744ac79-a84e-4f7d-bf30-34b9d90b9144\", \"1\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'threat_id' cannot be null","error":"error-exception","exception":{"class":"Doctrine\\DBAL\\Exception\\NotNullConstraintViolationException","file":"/var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php","line":125,"message":"An exception occurred while executing 'UPDATE amvs SET status = ?, updater = ?, threat_id = ?, anr_id = ?, vulnerability_id = ?, updated_at = ? WHERE uuid = ? AND anr_id = ?' with params [false, \"Admin Admin\", null, null, null, \"2021-07-07 11:27:24\", \"1744ac79-a84e-4f7d-bf30-34b9d90b9144\", \"1\"]:\n\nSQLSTATE[23000]: Integrity constraint violation: 1048 Column 'threat_id' cannot be null","stacktrace":"#0 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(182): Doctrine\\DBAL\\Driver\\AbstractMySQLDriver->convertException()\n#1 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/DBALException.php(159): Doctrine\\DBAL\\DBALException::wrapException()\n#2 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(2214): Doctrine\\DBAL\\DBALException::driverExceptionDuringQuery()\n#3 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1526): Doctrine\\DBAL\\Connection->handleExceptionDuringQuery()\n#4 /var/lib/monarc/fo/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(1475): Doctrine\\DBAL\\Connection->executeStatement()\n#5 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(505): Doctrine\\DBAL\\Connection->executeUpdate()\n#6 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/Persisters/Entity/BasicEntityPersister.php(394): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->updateTable()\n#7 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(1172): Doctrine\\ORM\\Persisters\\Entity\\BasicEntityPersister->update()\n#8 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/UnitOfWork.php(407): Doctrine\\ORM\\UnitOfWork->executeUpdates()\n#9 /var/lib/monarc/fo/vendor/doctrine/orm/lib/Doctrine/ORM/EntityManager.php(371): Doctrine\\ORM\\UnitOfWork->commit()\n#10 /var/lib/monarc/fo/vendor/monarc/core/src/Model/Db.php(358): Doctrine\\ORM\\EntityManager->flush()\n#11 /var/lib/monarc/fo/vendor/monarc/core/src/Model/Db.php(338): Monarc\\Core\\Model\\Db->flush()\n#12 /var/lib/monarc/fo/vendor/monarc/core/src/Model/Table/AbstractEntityTable.php(310): Monarc\\Core\\Model\\Db->save()\n#13 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Service/AnrAmvService.php(201): Monarc\\Core\\Model\\Table\\AbstractEntityTable->save()\n#14 /var/lib/monarc/fo/vendor/monarc/frontoffice/src/Controller/ApiAnrAbstractController.php(169): Monarc\\FrontOffice\\Service\\AnrAmvService->patch()\n#15 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(409): Monarc\\FrontOffice\\Controller\\ApiAnrAbstractController->patch()\n#16 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\\Mvc\\Controller\\AbstractRestfulController->onDispatch()\n#17 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\\EventManager\\EventManager->triggerListeners()\n#18 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractController.php(103): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#19 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Controller/AbstractRestfulController.php(312): Laminas\\Mvc\\Controller\\AbstractController->dispatch()\n#20 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/DispatchListener.php(138): Laminas\\Mvc\\Controller\\AbstractRestfulController->dispatch()\n#21 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(331): Laminas\\Mvc\\DispatchListener->onDispatch()\n#22 /var/lib/monarc/fo/vendor/laminas/laminas-eventmanager/src/EventManager.php(188): Laminas\\EventManager\\EventManager->triggerListeners()\n#23 /var/lib/monarc/fo/vendor/laminas/laminas-mvc/src/Application.php(331): Laminas\\EventManager\\EventManager->triggerEventUntil()\n#24 /var/lib/monarc/fo/public/index.php(34): Laminas\\Mvc\\Application->run()\n#25 {main}"}}]},"status":500,"config":{"method":"PATCH","transformRequest":[null],"transformResponse":[null],"jsonpCallbackParam":"callback","data":{"status":false},"url":"api/client-anr/1/amvs/1744ac79-a84e-4f7d-bf30-34b9d90b9144","headers":{"Accept":"application/json, text/plain, */*","Content-Type":"application/json;charset=utf-8","token":"e1ba94f8d95f916462082fd9f131f02311689b44a162795a23484c2493046bd5a327eceb1e60e5716e3f8b92.14578864"},"cached":false},"statusText":"Internal Server Error","xhrStatus":"complete","resource":{"status":false}}
	(anonyme Funktion) (angular-common-libs.js:100:195)
	g (angular-common-libs.js:141:143)
	$digest (angular-common-libs.js:153)
	$apply (angular-common-libs.js:156:492)
	k (angular-common-libs.js:107:452)
	v (angular-common-libs.js:113)
	(anonyme Funktion) (angular-common-libs.js:113:466)`

**Comment by ruslanbaidan** [comment]
Hi,
There is no issue anymore on our cloud Monarc instances, you can login at your and test it.
Might be your update was not complete: cache folder, Doctrine proxies cleanup etc.

**Comment by ruslanbaidan** [comment]
I reviewed the changes again, and there is no need to clean cache for this exact issue fix, but for others of course yes.
If you still get the error, your version is not up to date with the backend changes.
What you can do is to 1st test on our side to be sure it works in your instance on our cloud.
If it works, then your update was not successful:
- validate composer if it is the latest one.
- try to reinstall dependencies: composer ins -o --no-cache --no-dev

**Comment by KonzeptAcht** [comment]
Sorry, my fault. Reinstalling the dependencies helped.
